spring:
  application:
    name: linkforge
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  profiles:
    active:
      - dev

# snowflake properties
snowflake:
  epoch: 1770522213000   # 2026-02-08
  worker-id-bits: 10
  sequence-bits: 12
  worker-id: 1